{% set name = "orange-canvas-core" %}
{% set version = "0.2.5" %}

# on our linux builders there is no X11 installed and therefore import
# test will fail
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
{% set enable_testingui = true %}
{% else %}
{% set enable_testingui = false %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biolab/{{ name }}/archive/refs/tags/0.2.5.tar.gz
  sha256: 302768229eab2497bc900d7dcbedd913b6d6fa6c1d336593dbe3e19abc49cf53

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - trubar
  run:
    - python
    - anyqt >=0.2.0
    - docutils
    - commonmark >=0.8.1
    - requests
    - requests-cache
    - dictdiffer
    - qasync >=0.10.0
    - packaging
    - numpy
    - importlib_metadata >=4.6  # [py<310]
    - importlib_resources  # [py<39]

test:
  imports:
    - orangecanvas
  commands:
    - pip check
  requires:
    - pip
    - typing-extensions

about:
  home: https://github.com/biolab/orange-canvas-core
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Core component of Orange Canvas
  description: |
    Orange Canvas Core is is a framework for building graphical user
    interfaces for editing workflows. It is a component used to build
    the Orange Canvas (http://orange.biolab.si) data-mining application
    (for which it was developed in the first place).
  doc_url: https://github.com/biolab/orange-canvas-core/blob/master/README.rst
  dev_url: https://github.com/biolab/orange-canvas-core

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
