{% set name = "orange-canvas-core" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/biolab/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b9dce79635f83e4ac43f3acb0ced75f0ecfe3482bde92774c4294637a3352fa1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - trubar >=0.3.3
  run:
    - python
    - anyqt >=0.2.0
    - docutils
    - commonmark >=0.8.1
    - requests
    - requests-cache
    - dictdiffer
    - qasync >=0.10.0
    - typing-extensions
    - packaging
    - numpy
    - truststore

test:
  imports:
    - orangecanvas
  commands:
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip check
    - export QT_QPA_PLATFORM=offscreen  # [unix]
    - pytest --pyargs orangecanvas
  requires:
    - pip
    - pytest    

about:
  home: https://github.com/biolab/orange-canvas-core
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Core component of Orange Canvas
  description: |
    Orange Canvas Core is is a framework for building graphical user interfaces
    for editing workflows. It is a component used to build the Orange Canvas
    data-mining application (for which it was developed in the first place).
  doc_url: https://github.com/biolab/orange-canvas-core/blob/master/README.rst
  dev_url: https://github.com/biolab/orange-canvas-core

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
